k8s_version:
k8s_initializer:
k8s_controlnodes:
k8s_workernodes:
k8s_ip_range:
k8s_ip_range_controlnode:
k8s_ip_range_workernode:
k8s_ip_range_service:
k8s_ip_range_pod:
k8s_control_plane_endpoint:
k8s_private_control_plane_endpoint_ip:
k8s_private_control_plane_endpoint_port:
k8s_private_control_plane_endpoint_alias: "{{ k8s_cluster_name }}-control"
k8s_private_control_plane_endpoint: "{{ k8s_private_control_plane_endpoint_alias }}:{{ k8s_private_control_plane_endpoint_port }}"
k8s_apiserver_cert_extra_sans: []
k8s_hcloud_token:
k8s_cluster_name:
k8s_ingress:
k8s_cni:
k8s_registry_mirrors: {}
