- hosts: localhost
  gather_facts: true
  tasks:
    - name: Read kube config from initializer
      delegate_to: "{{ hostvars[groups.node|first].k8s_initializer }}"
      slurp:
        src: /etc/kubernetes/admin.conf
      register: k8s_admin_conf_result

    - name: Create kube config directory
      file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory

    - name: Write kube config
      vars:
        k8s_control_plane_endpoint: "{{ hostvars[groups.node|first].k8s_control_plane_endpoint }}"
        k8s_private_control_plane_endpoint: "{{ hostvars[groups.node|first].k8s_private_control_plane_endpoint }}"
      copy:
        content: "{{ k8s_admin_conf_result.content|b64decode|replace(k8s_private_control_plane_endpoint, k8s_control_plane_endpoint) }}"
        dest: "{{ ansible_env.HOME }}/.kube/config"
