controller:
  kind: DaemonSet
  hostNetwork: true
  service:
    type: ""
  config:
    use-proxy-protocol: "{{ 'true' if k8s_ingress_proxy_protocol else 'true' }}"
    hsts-max-age: 63072000
    hsts-include-subdomains: false
