- when: inventory_hostname == k8s_initializer
  block:
    - name: Install pip
      apt:
        name: python3-pip

    - name: Install openshift Python package
      pip:
        name: openshift==0.11.2
