- when:
    - inventory_hostname == k8s_initializer
    - k8s_cni in ('cilium', 'cilium-wireguard')
  block:
    - name: Install cilium
      loop:
        - "{{ k8s_cni }}.yaml"
      k8s:
        inline: |
          {{ lookup('template', 'cilium/' + item) }}
