- when:
    - inventory_hostname == k8s_initializer
    - k8s_cni in ('cilium', 'cilium-ipsec')
  block:
    - name: Generate IPsec keys for Cilium
      when: k8s_cni == 'cilium-ipsec'
      args:
        executable: bash
      shell: |
        if kubectl describe -n kube-system secret cilium-ipsec-keys; then
          exit 78
        fi
        kubectl create -n kube-system secret generic cilium-ipsec-keys \
            --from-literal=keys="3 rfc4106(gcm(aes)) $(echo $(dd if=/dev/urandom count=20 bs=1 2> /dev/null| xxd -p -c 64)) 128"
      register: k8s_cilium_generate_ipsec_keys
      changed_when: k8s_cilium_generate_ipsec_keys.rc != 78
      failed_when: k8s_cilium_generate_ipsec_keys.rc not in (0, 78)

    - name: Install Cilium
      loop:
        - "{{ k8s_cni }}.yaml"
      k8s:
        inline: |
          {{ lookup('template', 'cilium/' + item) }}
