- when:
    - inventory_hostname == k8s_initializer
    - k8s_cni == "cilium"
  block:
    - name: Install cilium
      loop:
        - cilium.yaml
      k8s:
        inline: |
          {{ lookup('template', 'cilium/' + item) }}
