- when: inventory_hostname == k8s_initializer
  block:
    - name: Install hcloud-ccm
      loop:
        - hcloud-ccm-secrets.yaml
        - hcloud-ccm.yaml
      k8s:
        inline: |
          {{ lookup('template', 'hcloud-ccm/' + item) }}
