- when: inventory_hostname == k8s_initializer
  block:
    - name: Initialize K8s cluster
      args:
        executable: bash
        creates: /etc/kubernetes/admin.conf
      shell: >
        kubeadm init
        --kubernetes-version=v{{ k8s_version|quote }}
        --service-cidr={{ k8s_ip_range_service|quote }}
        {% if k8s_install_hcloud_ccm %}--pod-network-cidr={{ k8s_ip_range_pod|quote }}{% endif %}
        --control-plane-endpoint={{ k8s_private_control_plane_endpoint|quote }}
        {% for san in k8s_apiserver_cert_extra_sans %}--apiserver-cert-extra-sans={{ san|quote }}{% if not loop.last %} {% endif %}{% endfor %}
        --apiserver-advertise-address={{ ansible_all_ipv4_addresses|ipaddr(k8s_ip_range_controlnode)|first }}
        --node-name={{ inventory_hostname }}
        --token-ttl=10m
      register: k8s_initialize_cluster_result
