- name: Create drop-in directory for kubelet service
  file:
    path: /etc/systemd/system/kubelet.service.d
    state: directory

- name: Template kubelet service overrides
  copy:
    content: |
      [Service]
      Environment=KUBELET_EXTRA_ARGS="--cloud-provider=external --cgroup-driver=systemd --node-ip={{ ansible_all_ipv4_addresses|ipaddr(k8s_ip_range_controlnode if inventory_hostname in k8s_controlnodes else k8s_ip_range_workernode)|first }}"
    dest: /etc/systemd/system/kubelet.service.d/ansible.conf
  notify: Restart kubelet

- name: Install kubelet
  apt:
    name: "kubelet={{ k8s_version }}-00"

- name: Prevent kubelet from being upgraded
  dpkg_selections:
    name: kubelet
    selection: hold

- name: Enable kubelet
  systemd:
    daemon_reload: true
    name: kubelet
    enabled: true

- name: Start kubelet
  systemd:
    name: kubelet
    state: started
  register: k8s_start_kubelet_result

- meta: flush_handlers
