- when:
    - inventory_hostname == k8s_initializer
    - k8s_install_reloader
  block:
    - name: Install reloader
      loop:
        - reloader-ns.yaml
        - reloader.yaml
      k8s:
        namespace: kube-reloader
        inline: |
          {{ lookup('template', 'reloader/' + item) }}
        wait: true
