- name: Install kubeadm and kubectl
  apt:
    name:
      - "kubeadm={{ k8s_version }}-00"
      - "kubectl={{ k8s_version }}-00"

- name: Prevent kubeadm and kubectl from being upgraded
  loop:
    - kubeadm
    - kubectl
  dpkg_selections:
    name: "{{ item }}"
    selection: hold

- when: inventory_hostname in k8s_controlnodes
  block:
    - name: Install kubectl and etcd-client
      apt:
        name:
          - etcd-client
