- name: Generate token to add node to cluster
  delegate_to: "{{ ansible_play_hosts_all|first }}"
  args:
    executable: /usr/bin/bash
  shell: |
    set -e -o pipefail
    microk8s add-node | grep -o 'microk8s join [a-z0-9:/\.]*' | awk '{print $3}'
  register: microk8s_add_node_result

- name: Add node to cluster
  shell: |
    microk8s join {% for link in microk8s_add_node_result.stdout_lines %}{% if link.split(':')[0]|ipaddr(cluster_network_ip_range) %}{{ link|quote }}{% endif %}{% endfor %}
